# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
client_id = "155b7606b434f4003fdd811236a1b064"
name = "Atelier Virtual AR Try-On"
application_url = "https://carefree-joy-production-c3b8.up.railway.app"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
scopes = "read_products,read_themes,write_products,write_themes"
optional_scopes = []
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://carefree-joy-production-c3b8.up.railway.app/auth/callback",
  "https://carefree-joy-production-c3b8.up.railway.app/auth/shopify/callback"
]
